### ISSUE TITLE
breeser.speed command forces recirculation mode

### ISSUE THREAD

**Issue by dummylabs** [airens/tion#4]
Thank you for the great library! I have an issue with changing the fan speed. When I try to set breeser's zone into the `manual` mode and then issue the `breeser.speed` command the speed changes accordingly, but it also takes Tion 3S into the recirculation mode instead of air intake mode which was set before. The behaviour is the same using the python library and the home assistant custom component.

**Comment by airens** [comment]
For some reasons, Tion server activate recirculation when it's not specified. Now (in version 0.71), it's forcelly set to previous state, when `send()` function is used in `manual` zone mode. Also, you can change air source by setting `gate` parameter of `Breezer` now.
